baseURL: "https://gautieggertsson.github.io/gauti_website/"
title: Gauti B. Eggertsson
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: Research
          url: research/
          weight: 2
        - name: Replication Files
          url: data/
          weight: 3
        - name: Teaching Materials
          url: courses/
          weight: 4
        - name: CV
          url: cv/
          weight: 5
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=6-MmtygAAAAJ&hl=en
          weight: 6
        - name: REPEC
          url: https://ideas.repec.org/e/peg7.html
          weight: 7 
        - name: Podcasts
          url: podcasts/
          weight: 8
        - name: Iceland
          url: iceland/
          weight: 9        
        - name: Blog
          url: https://gautieggertsson.blogspot.com/
          weight: 10

params:
    description: "Gauti B. Eggertsson is a macroeconomist and a Professor of Economics at Brown University Economics Department.
     He received his Ph.D. in Economics from Princeton University in 2004, after having completed his B.S. in economics from the University of Iceland.
      He has worked at Research Departments of the International Monetary Fund and the Federal Reserve Bank of New York.
       Since graduation he has also been visiting faculty at Princeton, Yale,
        and Columbia where he taught international finance and macroeconomics at both graduate and undergraduate level.
         Eggertsson has published in a variety of professional journals such as the American Economic Review, American Economic Journal:
          Macroeconomics, American Economic Review: Insights, Brookings Papers on Economics Activity, Economic Journal, Journal of Monetary Economics,
           Journal of Money, Credit and Banking, Review of Economic Studies, Review of Economic Dynamics and the Quarterly Journal of Economics.
            The main focus of his work is the analysis of monetary and fiscal policy over the business cycle, both from a modern and historical perspective."
    author: Gauti B. Eggertsson
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","research","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: >
           Gauti Bergþóruson Eggertsson, Professor of Economics at Brown
          subtitle: > 
           <p style='text-align: justify;'>Gauti B. Eggertsson is a macroeconomist and a Professor of Economics at Brown University Economics Department. He received his Ph.D. in Economics from Princeton University in 2004, after having completed his B.S. in economics from the University of Iceland. He has worked at Research Departments of the International Monetary Fund and the Federal Reserve Bank of New York. Since graduation he has also been visiting faculty at Princeton, Yale, and Columbia where he taught international finance and macroeconomics at both graduate and undergraduate level. Eggertsson has published in a variety of professional journals such as the American Economic Review, American Economic Journal: Macroeconomics, American Economic Review: Insights, Brookings Papers on Economics Activity, Economic Journal, Journal of Monetary Economics, Journal of Money, Credit and Banking, Review of Economic Studies, Review of Economic Dynamics and the Quarterly Journal of Economics. The main focus of his work is the analysis of monetary and fiscal policy over the business cycle, both from a modern and historical perspective.</p>
          imageUrl: "gauti_pic.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Replication Files
              url: data/
            - name: Teaching Materials
              url: courses/
            - name: CV
              url: cv/
            - name: Google Scholar
              url: https://scholar.google.com/citations?user=6-MmtygAAAAJ&hl=en
            - name: REPEC
              url: https://ideas.repec.org/e/peg7.html 
            - name: Podcasts
              url: podcasts/
            - name: Iceland
              url: iceland/
            - name: Blog
              url: https://gautieggertsson.blogspot.com/

    socialIcons:
        - name: Email
          url: mailto:gauti_eggertsson@brown.edu
        - name: Substack
          url: 

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Gauti B. Eggertsson"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2